### ISSUE TITLE
All arguments are dropped, breaking downstream images

### ISSUE THREAD

**Issue by rohansingh** [renovatebot/docker-buildpack#15]
It looks like #13 broke this image pretty badly. Prior to that being merged:

```
docker run --rm renovate/buildpack:1@sha256:e2e416bf17d2e58a8a6042a15dcb559048b11bc5e3143b7c7a33d38e01d8236a bash -c 'echo hello'
hello
```

And after that being merged:

```
docker run --rm renovate/buildpack:1@sha256:10e98460170e2ed4ea5150f5baefe0589c60bd8c63bf1f06fac5b8a61b61040d bash -c 'echo hello'

```

In the second example, bash runs but there is no output. All arguments are silently dropped. This breaks things like the renovate/go image.

**Comment by viceice** [comment]
Thanks for the fix
