### ISSUE TITLE
Support custom certs handling

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-buildpack#158]
Some users have custom SSL certificates, which means they need to manually apply changes to most/all tools which are installed. Something like the following would be great:

- Check for an env variable like `CUSTOM_SSL_CERTS`
- If present, try to set them up automatically for each of the tools we support (e.g. `NODE_EXTRA_CA_CERTS`)

Also including setting them up in OpenSSL itself, which hopefully many tools support.

---
**Environment**
- `SSL_CERT_FILE=/test/ca.pem` works for openssl based tools
  - curl
  - dotnet
  - erlang
  - go
  - php
  - python
  - ruby
  - rust
-  `NODE_EXTRA_CA_CERTS=/test/ca.pem`  for nodejs
- *Unknown*
  - swift (uses BoringSSL, openssl fork, maybe work too with `SSL_CERT_FILE`)

**References**
- https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html#DESCRIPTION
- https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file
- https://github.com/golang/go/blob/d4b26382342c98a95b85140b2863bc30c48edd68/src/crypto/x509/root_unix.go#L20
- https://github.com/rust-lang/cargo/issues/3676
- http://erlang.org/documentation/doc-5.8.4/lib/ssl-4.1.5/doc/html/notes.html
- https://github.com/apple/swift-nio-ssl/blob/cc0e80dbccf8c89c1f49c3a11c5929575035076c/Sources/CNIOBoringSSL/crypto/x509/x509_def.c#L73

**Comment by viceice** [comment]
How should we handle this for Sidecar containers? Should a potencial user rebuild them with their custom certs?

Or should we better allow them to be passed by renovate on the fly?
- configure extra certs via env / config for renovate (maybe path to custom certs folder)
- renovate configures itself with those certs
- renovate mounts certs to child container
- child container finds certs and configures them on startup

**Comment by rarkins** [comment]
I'm happy for an initial release of this to only work at *build* time. It would be a very nice to have feature if custom certs can be done at runtime by mapping a cert into sidecar containers as you describe, but nobody has that requirement yet.

**Comment by viceice** [comment]
Java needs a fully own certstore 😕  so it's fully different to the other tools. How should we handle this?

**Comment by viceice** [comment]
The truststore can be redirected to another location at runtime with env options, depends on used tool how to pass to java

https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#CustomizingStores

**Comment by viceice** [comment]
`java -Djavax.net.ssl.trustStore=/test/cacerts.jks ...`

So we need to check every manager how to pass additional java options. Maybe we should have different certificate handlings for normal and java ? 🤔
