### ISSUE TITLE
Add global tool wrapper

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-buildpack#163]
**What to do**
To have better compability with other workflows we should add global wrapper for installed tools.
Those wrapper should source `BASH_ENV` and then call normal tool, so we have our prepared env loaded.

**Sample Jenkins**

- Container is started like `docker run  ... -d --rm renovatebot/node cat`
- creating a `/path/to/run.sh` shell script  with commands at shared dir.
- Executing commands by `docker exec <container-id> sh /path/to/run.sh`

The exec is calling default `sh` command in env, which will be linked to `dash`  on our ubuntu image.
Overwriting it to `bash` won't help, as it won't source `BASH_ENV`.
`exec` is also not calling entrypoint, so again no `BASH_ENV` sourcing.

**Solution**

creating shell wrapper like we did for node < 15

https://github.com/renovatebot/docker-buildpack/blob/7fe5151afcdd27f31406e93ed8ea6f38ccbd5464/src/node/buildpack/tools/node.sh#L39-L42

https://github.com/renovatebot/docker-buildpack/blob/97680db3aa9585245d6e666dbd39c915cf0beda3/src/base/buildpack/util.sh#L56-L76

**Comment by viceice** [comment]
This would also allow doing `docker exec <container> go --version` and other commands, which currently fail because of not loading our env

**Comment by rarkins** [comment]
So for each tool `x`, it would actually call a wrapper of ours, which would do env export and then call the real `x`?

Would the wrapper locate the real `x` using `$PATH` somehow (e.g. finding the *second* `x` in the path after itself) or would it simply "know" which path for `x` to use because we installed it?

**Comment by viceice** [comment]
the wrapper sources our env, after it the wrapper will be later in path so it simply calls the real x then. thats how it currently works for `node`.

**Comment by viceice** [comment]
Missing parts:
- add shell wrapper for install-pip
- add shell wrapper for install-gem
- java
- erlang
- docker
- php
- composer

**Comment by viceice** [comment]
see https://github.com/containerbase/buildpack/issues/21

**Comment by viceice** [comment]
Duplicate of containerbase/buildpack#21
