### ISSUE TITLE
Document supported install-tool commands in README

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-buildpack#19]
Can we perhaps have a lint test also to verify that all applicable build/* scripts appear in the docs?

**Comment by rarkins** [comment]
Should we keep listing which images are built based on that, or remove that?

**Comment by viceice** [comment]
> Can we perhaps have a lint test also to verify that all applicable build/* scripts appear in the docs?
sure, do you know an easy way?

> Should we keep listing which images are built based on that, or remove that?
I think we can remove that, as it has no valuable info for users. Maybe we cann add links to  the tests for samples
