### ISSUE TITLE
Fix npm global installing in node 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-buildpack#30]
Running a command like `npm install --global yarn` fails in the current images. Using `npx` may not always make sense, e.g. if we need to run `npm x` twice and `npm` currently takes up to 30 seconds to install.

We could make the install home part of `/home/ubuntu` or we could `mkdir -p /usr/lib/local/node_modules` and chown it to `ubuntu`.

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by viceice** [comment]
I think we should simply add prefix config

`NPM_CONFIG_PREFIX=~/.npm-global`

**Comment by rarkins** [comment]
It doesn't need us to create the folder in advance?

**Comment by viceice** [comment]
nope:
https://github.com/renovatebot/docker-buildpack/blob/5cadd54a8a78940693338f6f759e036be738fc36/test/node/Dockerfile#L30-L32

I've tested it and it works
