### ISSUE TITLE
Add dotnet 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-buildpack#53]
As per discussion in https://github.com/renovatebot/renovate/issues/6610

**Comment by viceice** [comment]
trying to do it today

**Comment by viceice** [comment]
@fgreinacher Do you think we only need latest dotnet cli, or should we add all lts / latest to a single image, or should we build multiple images like node / python / ... ?

**Comment by rarkins** [comment]
I thought we decided to install it dynamically as it only took 8 seconds? Just needs some libraries pre-installed

**Comment by fgreinacher** [comment]
> @fgreinacher Do you think we only need latest dotnet cli, or should we add all lts / latest to a single image, or should we build multiple images like node / python / ... ?

Hm, not sure. GitHub Actions installs all available non-preview SDKs (see https://github.com/actions/virtual-environments/blob/5fceca9626917b69cd9951fa974ebfd3990f829f/images/macos/provision/core/dotnet.sh#L22). That's obviously the safest choice but would increase the image size substantially... So we might start with latest LTS and non-LTS versions and see if that works for most people.

**Comment by viceice** [comment]
ok, found the install script: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

So preparing a simple image, which installs the prerequirements and the install script, so we only build a latest dotnet image and install the  required tools version on the fly.

**Comment by viceice** [comment]
This can be helpful too 🙃 

https://github.com/dotnet/dotnet-docker/blob/bc2436b836e35f87f854f5c6bea0ab3821505353/src/sdk/3.1/bionic/amd64/Dockerfile#L1
